DROP DATABASE IF EXISTS cad;

CREATE DATABASE IF NOT EXISTS cad;

USE cad;

CREATE TABLE IF NOT EXISTS usuario(
	id INT(11) PRIMARY KEY AUTO_INCREMENT,
  username VARCHAR(50) NOT NULL UNIQUE,
  email VARCHAR(150) NOT NULL UNIQUE,
  phoneNo VARCHAR(14) NOT NULL UNIQUE,
	pass VARCHAR(20) NOT NULL,
  pfpImage VARCHAR(500)
);